language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "pypy"
install:
  - pip install "mock>=1.0.1" "nose>=1.3.0" flake8
  - python setup.py clean build --build-base="build/$TRAVIS_PYTHON_VERSION" install
script:
  - nosetests -v --no-path-adjustment
  - flake8 --max-line-length=110 *.py
